title: Armaan Sethi
description: Things I find interesting
url: "https://armaansethi.github.io"

# Social links (used in header)
linkedin: armaan-sethi
github: ArmaanSethi
scholar: ofrMcnEAAAAJ

# Build settings
markdown: kramdown
